### ISSUE TITLE
Readd /owning to disable protection

### ISSUE THREAD

**Issue by TheZoq2** [Pheasn/BlockOwn#129]
A while ago you were able to temporarily turn off protection using /owning but that feature has seemingly been removed.

**Comment by Pheasn** [comment]
You wish to be able to disable the saving of the owner of blocks you place on a per-player basis ?

**Comment by TheZoq2** [comment]
Yes, just like the command worked before. Whenever you log on, protection is on, if you do /owning, none of your blocks get protected. Do /owning again and they do get protected again

**Comment by Pheasn** [comment]
I actually don't remember this was possible before. I will include that however

**Comment by TheZoq2** [comment]
Awesome, thanks
