### ISSUE TITLE
Some new features

### ISSUE THREAD

**Issue by Greenman1805** [Pheasn/BlockOwn#140]
I have two ideas for your plugin.

The first one is, when a player has not joined for X days, his protections will be deleted. Is this possible? Maybe with a command like /purgeprotections <days>

Can you also add something like a command where you're able to transfer Worldedit selected blocks to another player? Like /transfer <playername> 

Would be nice :)

**Comment by Pheasn** [comment]
Thanks for the suggestions, this issue was split into issues #141 #142 and #143
